name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
    pull_request:
        paths:
            - '**.jpg'
            - '**.jpeg'
            - '**.png'
            - '**.webp'

jobs:
  build:
    name: compress_images
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Compress Images
        uses: ZeckWork/compress-images@v2?random=${{ github.run_id }}

      # - name: Compress Images
      #   uses: calibreapp/image-actions@main
      #   with:
      #     githubToken: ${{ secrets.GITHUB_TOKEN }}
      #     onlyImagesInPR: true